config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
	get  '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete  '/logout', to: 'sessions#destory'
	resources :users do
    member do
      get :following, :followers
    end
  end
	resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms do
    post 'add_users', on: :member
    post 'message_create', on: :member
  end
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :users , through: :entries
  has_many :messages, dependent: :destroy
  validates :name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user

  def index
    @rooms = current_user.rooms.paginate(page: params[:page])
    # index page have form
    @room = current_user.rooms.new
  end

  def show
    room = Room.find(params[:id])
    @room_users = room.users
    @messages = room.messages
    @message = room.messages.new
  end

  def create
    user = current_user
    room = user.rooms.new(room_params)
    if user.save
    	flash[:success] = "Room created"
    	redirect_to rooms_url
    else
      flash[:danger] = "Room not created"
    	render 'index'
    end
  end

  def destroy
    Room.find(params[:id]).destroy
    flash[:success] = "Room deleted"
    redirect_to rooms_url
  end

  def add_users
    room = Room.find(params[:id])
    user = User.find_by(atmark: params[:atmark])
    entry = Entry.new(user_id: user&.id, room_id: room&.id)
    if entry.save
      flash[:success] = "Add User"
    else
      flash[:danger] = "Not Add User"
    end
    redirect_to room_url
  end

  def message_create
    room = Room.find(params[:id])
    message = room.messages.new(message_params)
    if message.save
      flash[:success] = "Message created"
    else
      flash[:danger] = "Message not created"
    end
    redirect_to room_url
  end

  private

	def room_params
    params.require(:room).permit(:name)
  end
  
  def message_params
    params.require(:message).permit(:message).merge(send_user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.slim
h1
  | DM
.row
  .col-md-8.col-md-offset-2
    - if @rooms&.any?
      .list-group
        - @rooms.each do |room|
          .list-group-item
            | ルーム名 : 
            = link_to room.name, room
            = link_to "delete", room, method: :delete, data: { confirm: "You sure?" },
              class: 'pull-right badge progress-bar-danger'
    = form_with model: @room, local: true do |f|
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.submit "Create New room", class: "btn btn-primary"

app/views/rooms/show.html.slim
h1
  | DM show

.row
  .col-md-7.col-md-offset-1

    - if @messages.exists?
      .list-group
        - @messages.each_with_index do |message, index|
          - next if index == (@messages.size - 1)
          .list-group-item
            = message.message

    = form_with model: @message, url: message_create_room_path, local: true do |f|
      = f.label :message
      = f.text_field :message, class: 'form-control'
      = f.submit "Create Message", class: "btn btn-primary btn-sm"


  .col-md-3
    h3
      | Room User
    .list-group
      - @room_users.each do |room_user|
        .list-group-item
          = room_user.name
    = form_with url: add_users_room_path, local: true do |f|
      = f.label :atmark
      = f.text_field :atmark, class: 'form-control'
      = f.submit "Add user to Room", class: "btn btn-primary"