config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
	get  '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete  '/logout', to: 'sessions#destory'
	resources :users do
    member do
      get :following, :followers
    end
  end
	resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms do
    post 'add_users', on: :member
    post 'message_create', on: :member
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    |  The 
    a[href="https://railstutorial.jp/"]
      | Ruby on Rails Tutorial
    |  by 
    a[href="http://www.michaelhartl.com/"]
      | Michael Hartl
  nav
    ul
      li
        = link_to "About",   about_path
      li
        = link_to "Contact", contact_path
      li
        a[href="http://news.railstutorial.org/"]
          | News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "sample app", root_path, id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Home", root_path
        li
          = link_to "Help", help_path
        - if logged_in?
          li
            = link_to "DM", rooms_path
          li
            = link_to "Users", users_path
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              |  Account 
              b.caret
            ul.dropdown-menu
              li
                = link_to "Profile", current_user
              li
                = link_to "Settings", edit_user_path(current_user)
              li.divider
              li
                = link_to "Log out", logout_path, method: :delete
        - else
          li
            = link_to "Log in", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        |  <div class="alert alert-
        = message_type
        | ">
        = message
    = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?